# Generated by Django 2.0.2 on 2019-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
