# Generated by Django 2.1.5 on 2019-10-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='des',
            field=models.TextField(null=True),
        ),
    ]
